name: 'Github Action Wrike PR Sync'
description: 'Updates Wrike tasks based on Github PRs'
inputs:
  WRIKE_ACCESS_TOKEN:
    description: 'Your permanent wrike api token.'
    required: true
  WRIKE_IN_REVIEW_STATE_ID:
    description: 'Your "In Review" ticket state ID in Wrike.'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'square'
  color: 'green'
