name: 'Github Action Wrike PR Sync'
description: 'Updates Wrike tasks based on Github PRs'
inputs:
  WRIKE_ACCESS_TOKEN:
    description: 'Your permanent wrike api token.'
    required: true
  WRIKE_IN_REVIEW_STATE:
    description: 'Your "In Review" ticket state in Wrike.'
    required: true
  WRIKE_MERGED_STATE:
    description: 'Your "After merge" ticket state in Wrike.'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'square'
  color: 'green'
